### ISSUE TITLE
npx sequelize-cli db:migrate:all  not working 

### ISSUE THREAD

**Issue by manish-saini-dev** [Mahanteshkumbar/Nodejs-EJS-Role-JWToken-Auth-SequilizeMigration-Express-Framework#1]
![image](https://user-images.githubusercontent.com/75108475/188066261-ffd17220-dfdc-4759-a0ef-bf3e5d32b56e.png)
sir 

PS C:\xampp\htdocs\admin-node> npx sequelize-cli db:migrate:all
   
error showing
 Unknown arguments: config, models-path, modelsPath, seeders-path, seedersPath, migrations-path, migrationsPath, db:migrate:all

**Comment by rahulcheni** [comment]
I tried and is working
 npx sequelize db:migrate
npx sequelize db:seed:all

**Comment by Mahanteshkumbar** [comment]
@rahulcheni 
Thanks for the comment. 
Hence closing this issue
